# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

target 'SimiCart' do
  rn_maps_path = '../node_modules/react-native-maps'
  rn_camera_path = '../node_modules/react-native-camera'
  rn_camera_subpodspec = [
    'BarcodeDetectorMLKit'
  ]

  pod 'React', :path => '../node_modules/react-native/'
    pod 'React-Core', :path => '../node_modules/react-native/React'
    pod 'React-DevSupport', :path => '../node_modules/react-native/React'
    pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
    pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
    pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
    pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
    pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
    pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
    pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
    pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
    pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'
    pod 'React-RCTWebSocket', :path => '../node_modules/react-native/Libraries/WebSocket'
    pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
    pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
    pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
    pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'
    pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
    pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
    pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
    pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  pod 'Firebase/Core', '~> 6.13.0'
  pod 'Firebase/Messaging', '~> 6.13.0'
  pod 'Firebase/DynamicLinks', '~> 6.13.0'

  # pod 'ReactNativePermissions', :path => '../node_modules/react-native-permissions'
  pod 'RNFirebase', :path => '../node_modules/react-native-firebase/ios'
  pod 'RCTRestart', :path => '../node_modules/react-native-restart/ios'

  pod 'react-native-onesignal', :path => '../node_modules/react-native-onesignal'

  pod 'Fabric'
  pod 'Crashlytics'
  pod 'GoogleDataTransport'
  
  pod 'FBSDKCoreKit', '~> 12.2.1'
  pod 'FBSDKLoginKit', '~> 12.2.1'
  pod 'FBSDKShareKit', '~> 12.2.1'

  #pod 'YandexMobileMetrica', '3.4.1'

  pod 'react-native-tracking-transparency', :path => '../node_modules/react-native-tracking-transparency'
  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'


  pod 'react-native-fbsdk-next', :path => '../node_modules/react-native-fbsdk-next'

  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-community/async-storage'

  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

  pod 'RNReanimated', :path => '../node_modules/react-native-reanimated'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'

  pod 'react-native-netinfo', :path => '../node_modules/@react-native-community/netinfo'

  pod 'RNAwesomeCardIO', :path => '../node_modules/react-native-awesome-card-io'

  pod 'react-native-geolocation', :path => '../node_modules/@react-native-community/geolocation'

  pod 'RNCPushNotificationIOS', :path => '../node_modules/@react-native-community/push-notification-ios'

  pod 'react-native-webview', :path => '../node_modules/react-native-webview'

  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

  pod 'react-native-cookies', :path => '../node_modules/@react-native-community/cookies'

  pod 'react-native-voice', :path => '../node_modules/@react-native-community/voice'

end

post_install do |installer|
  installer.pods_project.build_configurations.each do |config|
    config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
  end
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
    end
    if target.name == 'react-native-google-maps'
      target.build_configurations.each do |config|
        config.build_settings['CLANG_ENABLE_MODULES'] = 'No'
      end
    end
    if target.name == 'RNFirebase'
        target.build_configurations.each do |config|
            config.build_settings['HEADER_SEARCH_PATHS'] = '$(inherited) ${PODS_ROOT}/Headers/Public/**'
        end
    end
    if target.name == "React"
      target.remove_from_project
    end
    if target.name == "yoga"
      target.remove_from_project
    end
  end
  find_and_replace("../node_modules/react-native/React/CxxBridge/RCTCxxBridge.mm",
    "_initializeModules:(NSArray<id<RCTBridgeModule>> *)modules", "_initializeModules:(NSArray<Class> *)modules")
end

def find_and_replace(dir, findstr, replacestr)
  Dir[dir].each do |name|
      text = File.read(name)
      replace = text.gsub(findstr,replacestr)
      if text != replace
          puts "Fix: " + name
          File.open(name, "w") { |file| file.puts replace }
          STDOUT.flush
      end
  end
  Dir[dir + '*/'].each(&method(:find_and_replace))

bad_import = "<React/RCTResizeMode.h>"
      good_import = "<React-RCTImage/React/RCTResizeMode.h>"
      file_name = "pods/Headers/Private/RNFastImage/FFFastImageView.h"

  if File.file?(file_name)
      file = File.open(file_name)
      file_data = file.read
      file_data.sub! bad_import, good_import
      File.write(file_name, file_data)

      file_name = "pods/Headers/Public/RNFastImage/FFFastImageView.h"
      file = File.open(file_name)
      file_data = file.read
      file_data.sub! bad_import, good_import
      File.write(file_name, file_data)
    end
end
    