export default {
    simi_appwishlist_40: require('../../etc/events/plugins/simi_appwishlist_40/events').default,
    simi_fblogin_40: require('../../etc/events/plugins/simi_fblogin_40/events').default,
    magestore_storelocator_40 : require('./plugins/magestore_storelocator_40/events').default,
    simi_simicontact_40 : require('./plugins/simi_simicontact_40/events').default,
    simi_customchat_40 : require('./plugins/simi_customchat_40/events').default,
    simi_firebase_analytics_40: require('./plugins/simi_firebase_analytics_40/events').default,
    checkout_management_40: require('./plugins/checkout_management_40/events').default,
    simi_simimixpanel_40: require('./plugins/simi_simimixpanel_40/events').default,
    simi_searchvoice_40 : require('./plugins/simi_searchvoice_40/events').default,
    simi_simibarcode_40 : require('./plugins/simi_simibarcode_40/events').default,
    simi_simibraintree_40 : require('./plugins/simi_simibraintree_40/events').default,
    simi_paypalexpress_40: require('./plugins/simi_paypalexpress_40/events').default,
    simi_simigiftcard_40: require('./plugins/simi_simigiftcard_40/events').default,
    simi_simisocialshare_40: require('./plugins/simi_simisocialshare_40/events').default,
    magestore_productlabel_40: require('./plugins/magestore_productlabel_40/events').default,
    simi_simicustompayment_40: require('../../etc/events/plugins/simi_simicustompayment_40/events').default,
    simi_loyalty_40: require('../../etc/events/plugins/simi_loyalty_40/events').default,
    simi_simiproductreview_40: require('../../etc/events/plugins/simi_simiproductreview_40/events').default
}
